services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-net
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
    networks:
      - app-net


  prometheus:
    image: prom/prometheus:latest
    container_name: tsp-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - backend
    networks:
      - app-net

  node-exporter:
    image: prom/node-exporter:latest
    container_name: tsp-node-exporter
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro
    networks:
      - app-net

  grafana:
    image: grafana/grafana:latest
    container_name: tsp-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - app-net

networks:
  app-net:
    driver: bridge